# roles/tomcat/handlers/main.yml

- name: restart tomcat
  service: name={{ tomcat_service }} state=restarted
  sudo: yes

- name: reload tomcat
  service: name={{ tomcat_service }} state=reloaded
  sudo: yes

- name: start tomcat
  service: name={{ tomcat_service }} state=started
  sudo: yes

- name: stop tomcat
  service: name={{ tomcat_service }} state=stopped
  sudo: yes
